#!/bin/sh

stow_pkg() {
    [ -L "$2" ] && rm "$2"
    mkdir -p "$2" && stow -v --target="$2" "$1"
}

stow_pkg alacritty  "$HOME/.config/alacritty"
stow_pkg bash       "$HOME/.config/bash"
stow_pkg bin        "$HOME/.local"
stow_pkg fuzzel     "$HOME/.config/fuzzel"
stow_pkg git        "$HOME/.config/git"
stow_pkg mako       "$HOME/.config/mako"
stow_pkg nvim       "$HOME/.config/nvim"
stow_pkg nwg-bar    "$HOME/.config/nwg-bar"
stow_pkg ranger     "$HOME/.config/ranger"
stow_pkg rbw        "$HOME/.config/rbw"
stow_pkg starship   "$HOME/.config"
stow_pkg sway       "$HOME/.config/sway"
stow_pkg tmux       "$HOME/.config/tmux"
stow_pkg vim        "$HOME/.config/vim"
stow_pkg waybar     "$HOME/.config/waybar"
stow_pkg xdg-desktop-portal-wlr "$HOME/.config/xdg-desktop-portal-wlr"
stow_pkg zsh        "$HOME/.config/zsh"

stow_pkg systemd   "$HOME/.config/systemd"

HOST=$(cat /etc/hostname)
[ -d "host-$HOST" ] && stow -v --target="$HOME" "host-$HOST"
