format = "${custom.jclx}$all"

[character]
vicmd_symbol = "[](bold green)"

[custom.jclx]
command="echo $JCLX_STATUS | awk '{print $2}'"
when = "[[ \"$PWD\" == *\"jclexpert\"* ]]"
symbol = "⚙️"
style = "bold yellow"
