workspace_layout default
output DP-1 resolution 3840x1080@240Hz
output * bg /home/egg/Pictures/bg/uw/stray1.png fill

workspace 1:Terminal output DP-1
workspace 2:Firefox output DP-1
workspace 3:Steam output DP-1
workspace 4:Discord output DP-1

assign [app_id="Alacritty"]  workspace 1:Terminal
assign [app_id="firefox"]    workspace 2:Firefox
assign [app_id="steam"]      workspace 3:Steam
assign [app_id="discord"]    workspace 4:Discord

exec uwsm app -- alacritty
exec uwsm app -- firefox
exec uwsm app -- steam
exec uwsm app -- discord
