output * bg /home/dylanf/Pictures/Ngc6888Hoo_Aro_2466.jpg fill

output "AOC 2790 APSL69A001340" {
    resolution 1920x1080
    position 0,0
    transform 270
}
output "AOC 27E3 AUBQ69A000160" {
    resolution 1920x1080
    position 1080,0
}
output eDP-1 {
    resolution 1920x1200
    position 3000,0
}

workspace 1:Terminal output "AOC 2790 APSL69A001340"
workspace 2:Firefox output "AOC 27E3 AUBQ69A000160"
workspace 3:Teams output eDP-1

assign [app_id="Alacritty"] workspace 1:Terminal
assign [app_id="firefox"] workspace 2:Firefox
assign [app_id="teams-for-linux"] workspace 3:Teams

exec uwsm app -- teams-for-linux
exec uwsm app -- firefox
exec uwsm app -- alacritty
